### ISSUE TITLE
File Missing

### ISSUE THREAD

**Issue by danielloiola** [cconard96/glpi-assetaudit-plugin#2]
**Describe the bug**
The link of + button at the menu have reference to audit.form.php, but it's missing in the plugin...

**To Reproduce**
1. Go to Plugins -> Audit
2. Click on +
3. See error "File not found." plugins/assetaudit/front/audit.form.php

**Expected behavior**
Show the audit form...
![error 1](https://user-images.githubusercontent.com/85361832/128193079-f40bdb1f-a82c-499f-a08e-4f9c0f1ad733.png)
![error 2](https://user-images.githubusercontent.com/85361832/128193083-d837afa8-8ff5-4c9a-9771-d324d57b9fb1.PNG)

**Screenshots**

**System Specifications (please complete the following information):**
 - GLPI Server OS: [e.g. Fedora 30, Windows Server 2019, etc]
 - Browser [chrome, edge]
 - Plugin version [1.0.0]

**Comment by cconard96** [comment]
There is no release for this plugin yet so you are using a version that is still in development. Right now, only quick audits are implemented (just like older physicalinventory plugin).

I don't know when I'll have time to continue towards an official release but I'll let you know.

**Comment by danielloiola** [comment]
I saw this plugin and its exactly what we need here, Ill check with our dev team to fork and finish :-)

**Comment by cconard96** [comment]
If allowed by your company, I'd be happy to review any changes/new features to include them in this plugin for an official release. Hopefully things settle down here as we get past summer and closer towards the next major GLPI release and I'll have more time to develop this.

**Comment by danielloiola** [comment]
For sure, I`ll send updates for you :-) Ill be happy to share.
